---
- hosts: dev
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: multibranch
        image: "venkypn/multibranch:latest"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
